all:
  children:
    servers:
      children:
        k8s:
          hosts:
            cac.herocc.com:
              ansible_user: ubuntu
            10.0.1.10:
              ansible_user: dietpi
              ansible_ssh_transfer_method: scp


