---
- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: configure server components
  hosts: servers
  roles:
    - server

- name: configure kubernetes nodes
  hosts: k8s
  roles:
    - k8s
